In [ ]:
import numpy as np
from google.colab import files
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [ ]:
def linear_regression(x,w):
  return np.dot(x,w)

In [ ]:
def loss_function(x,y,w):
  return np.square(linear_regression(x,w)- y).sum() / (2 * (x.size))

In [ ]:
def gradient_step(x, y, w, learning_rate):
    m = len(y)
    grad = (x.T @ (linear_regression(x, w) - y)) / m
    w -= learning_rate * grad
    return w

In [ ]:
def gradient(x, y, learning_rate, num_iter, eps):
    ones = np.ones((x.shape[0], 1))
    x = np.hstack((ones, x))

    w = np.zeros(x.shape[1])

    loss = loss_function(x, y, w)
    loss_history = [loss]

    for _ in range(num_iter):
        w = gradient_step(x, y, w, learning_rate)

        loss = loss_function(x, y, w)
        if abs(loss - loss_history[-1]) < eps:
            loss_history.append(loss)
            break

        loss_history.append(loss)

    return w, loss_history

In [ ]:
uploaded = files.upload()

Saving Housing.csv to Housing (1).csv

In [ ]:
df = pd.read_csv('Housing.csv')
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [ ]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
features = ['area','bedrooms','bathrooms']
scaler = StandardScaler()
x = scaler.fit_transform(df[features])
y = df['price']

In [ ]:
w, loss_hist = gradient(x,y, learning_rate=0.1, num_iter= 10000, eps = 1e-6)
print(f'Gradient descent:{w[1:]}')

Gradient descent:[821214.14964171 299983.61442122 695808.47659399]

Gradient descent:[821214.16789549 299983.75008319 695808.33287788]

In [ ]:


w_analytical = np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)

print("Аналітичні коефіцієнти w:", w_analytical)

Аналітичні коефіцієнти w: [821214.14349519 299983.57107963 695808.52272537]

In [ ]:
lr_reg = LinearRegression()
lr_reg.fit(x,y)
print(f'LinearRegression: {lr_reg.coef_}')

LinearRegression: [821214.14349519 299983.57107963 695808.52272537]